export const metroStops = [
    "Aeroport",
    "Alameda",
    "Albalat dels Sorells",
    "Alberic",
    "Alboraia - Palmaret",
    "Alboraia Peris Aragó",
    "Alfauir",
    "Alginet",
    "Almàssera",
    "Amistat",
    "Àngel Guimerà",
    "Aragó",
    "Ausiàs March",
    "Av. del Cid",
    "Ayora",
    "Bailén",
    "Bétera",
    "Fondo de Benaguasil",
    "Benaguasil",
    "Benicalap",
    "Beniferri",
    "Benimaclet",
    "Benimàmet",
    "Benimodo",
    "Burjassot",
    "Burjassot - Godella",
    "Campament",
    "Campanar",
    "Campus",
    "Cantereria",
    "Carlet",
    "Colón",
    "Col·legi El Vedat",
    "Dr. Lluch",
    "El Clot",
    "Empalme",
    "Entrepins",
    "Espioca",
    "Estadi Ciutat de València",
    "Platja Malva-rosa",
    "Facultats – Manuel Broseta",
    "Faitanar",
    "Fira València",
    "Florista",
    "Foios",
    "Font Almaguer",
    "Francesc Cubells",
    "Fuente del Jarro",
    "Garbí",
    "Godella",
    "Grau – La Marina",
    "Horta Vella",
    "Jesús",
    "L'Alcúdia",
    "L'Eliana",
    "La Cadena",
    "La Canyada",
    "La Carrasca",
    "La Coma",
    "La Cova",
    "La Granja",
    "Cabanyal",
    "La Pobla de Farnals",
    "La Pobla de Vallbona",
    "La Presa",
    "La Vallesa",
    "Platja les Arenes",
    "Les Carolines - Fira",
    "Ll. Llarga - Terramelar",
    "Llíria",
    "Machado",
    "Manises",
    "Marítim",
    "Neptú",
    "Marxalenes",
    "Mas del Rosari",
    "Masia de Traver",
    "Masies",
    "Massalavés",
    "Massamagrell",
    "Massarrojos",
    "Canyamelar",
    "Meliana",
    "Mislata",
    "Mislata - Almassil",
    "Moncada - Alfara",
    "Montesol",
    "Montortal",
    "Museros",
    "Nou d'Octubre",
    "Omet",
    "Orriols",
    "Paiporta",
    "Palau de Congressos",
    "Paterna",
    "Patraix",
    "Picanya",
    "Picassent",
    "Pl. Espanya",
    "Pont de Fusta",
    "Trinitat",
    "Quart de Poblet",
    "Rafelbunyol",
    "Realón",
    "Reus",
    "Riba-roja de Túria",
    "Rocafort",
    "Roses",
    "Safranar",
    "Sagunt",
    "Salt de l'Aigua",
    "Sant Isidre",
    "Sant Joan",
    "Sant Miquel dels Reis",
    "Sant Ramon",
    "Parc Científic",
    "Santa Rita",
    "Seminari - CEU",
    "Beteró",
    "Tarongers – Ernest Lluch",
    "Túria",
    "Tomás y Valiente",
    "Gallipont - Torre del Virrei",
    "Torrent",
    "Torrent Avinguda",
    "Tossal del Rei",
    "Trànsits",
    "À Punt",
    "Universitat Politècnica",
    "València la Vella",
    "València Sud",
    "Vicent Andrés Estellés",
    "Vicente Zaragozá",
    "Castelló",
    "Xàtiva",
    "Alacant",
    "Amado Granell-Montolivet",
    "Ciutat Arts i Ciències - Justícia",
    "Moreres",
    "Natzaret",
    "Oceanogràfic",
    "Quatre Carreres",
    "Russafa"
].sort();
